### ISSUE TITLE
Use Serverless Docker

### ISSUE THREAD

**Issue by sergiodxa** [felixheck/wheretheheck#1]
With https://zeit.co/blog/serverless-docker it's possible to let the service freeze without slow cold boot performance. Is just adding a simple Dockerfile like:

```Dockerfile
FROM mhart/alpine-node:base-10
WORKDIR /usr/src
ENV NODE_ENV="production"
COPY . .
CMD ["node", "index.js"]
```

And a `.dockerignore` with:

```
*
!index.js
```

> You only need the `index.js` since it doesn't have production dependencies

**Comment by felixheck** [comment]
Thanks for your message @sergiodxa — additionally, have to remove `scripts.start` from `package.json` and add related fields in `now.json` instead, right?

**Comment by sergiodxa** [comment]
Nice!
