### ISSUE TITLE
Now CDN-ready

### ISSUE THREAD

**Issue by sergiodxa** [felixheck/wheretheheck#3]
If you add Cache-Control headers to the server response with `s-maxage=a week in seconds` any user could enable Now CDN for the domain and rely on CDN for sending the redirect response instead of the API.

If the user doesn't have CDN enabled then it will do nothing.

**Comment by felixheck** [comment]
```
res.setHeader('Cache-Control', 'public, immutable, s-maxage=604800')
```

Just wondering because https://github.com/now-examples/redirect/pull/10/files uses a year instead of a week :)
